package main

import (
	"os"

	cl "github.com/mpmlj/clarifai-client-go"
)

func main() {

	var err error
	var sess *cl.Session
	if os.Getenv("CLARIFAI_API_KEY") != "" {
		sess = cl.NewApp(os.Getenv("CLARIFAI_API_KEY"))
	} else {
		sess, err = cl.Connect(os.Getenv("CLARIFAI_API_ID"), os.Getenv("CLARIFAI_API_SECRET"))
		if err != nil {
			panic(err)
		}
	}

	//// Create a model w/o custom ID, ID will be generated by Clarifai API.
	//resp, err := sess.CreateModel("test-model", nil).Do()
	//if err != nil {
	//	panic(err)
	//}

	// Create a model w/ options.
	opt := cl.NewModelOptions()
	opt.ID = "music-model-id-1"              // Set custom ID.
	opt.Concepts = []string{"music", "band"} // Add concepts.
	opt.ConceptsMutuallyExclusive = false
	opt.ClosedEnvironment = false

	resp, err := sess.CreateModel("music-model", opt).Do()
	if err != nil {
		panic(err)
	}

	cl.PP(resp)
}
